In [156]:
import pandas as pd
import numpy as np


In [157]:
df = pd.read_csv('all_features_2.csv', index_col= None)
df = df.drop('Unnamed: 0', axis=1)
# randomize the data
df = df.sample(frac=1).reset_index(drop=True)
df.head()

0      1     2      3     4      5     6      7     8      9  ...  \
0  67.0  102.0  71.0  124.0  76.0  144.0  80.0  164.0  87.0  182.0  ...   
1  75.0  102.0  75.0  122.0  75.0  142.0  77.0  163.0  84.0  180.0  ...   
2   NaN    NaN   NaN    NaN   NaN    NaN   NaN    NaN   NaN    NaN  ...   
3  73.0   97.0  76.0  119.0  81.0  141.0  85.0  162.0  92.0  181.0  ...   
4  69.0   95.0  70.0  116.0  74.0  136.0  77.0  157.0  84.0  176.0  ...   

        Width      Height  H_W_Ratio  Jaw_width  J_F_Ratio    MJ_width  \
0  158.050625  214.009346   1.354056  70.028566   0.443077  122.065556   
1  158.079094  222.000000   1.404360  74.006756   0.468163  132.003788   
2         NaN         NaN        NaN        NaN        NaN         NaN   
3  162.003086  234.136712   1.445261  72.000000   0.444436  126.000000   
4  159.000000  202.039600   1.270689  72.000000   0.452830  127.035428   

   MJ_J_width  filenum                       filename  classified_shape  
0    1.743082      164     Reese Witherspoon (19).jpg             heart  
1    1.783672     1022      Adrianne Palicki (25).jpg              long  
2         NaN     1268               mila kunis 8.png             round  
3    1.750000      111  Jennifer Love Hewitt (11).jpg             heart  
4    1.764381     1234         Kirsten Dunst (13).jpg             round  

[5 rows x 170 columns]

In [158]:
from sklearn import metrics
from sklearn.metrics import pairwise_distances
from sklearn.preprocessing import normalize
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn import ensemble
from sklearn import linear_model
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler  
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.decomposition import PCA 

In [159]:
data = df.dropna(axis=0, how='any')
X = data
X = X.drop(['filenum','filename','classified_shape'] , axis = 1)
X_norm = normalize(X)
Y = data['classified_shape']
Y.head()

0    heart
1     long
3    heart
4    round
5    heart
Name: classified_shape, dtype: object

In [160]:
scaler = StandardScaler()  
scaler.fit(X)  

X = scaler.transform(X)

In [161]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,Y,
    test_size=0.25,
    random_state=1200)

In [162]:
n_components = 18
pca = PCA(n_components=n_components, svd_solver='randomized',
          whiten=True).fit(X)

X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)

In [163]:
# #Remove PCA 
X_train_pca = X_train
X_test_pca = X_test

In [164]:
# train a LDA classifier and print the accuracy and confusion matrix
lda = LinearDiscriminantAnalysis()
lda.fit(X_train_pca, Y_train)
Y_pred = lda.predict(X_test_pca)
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))


Accuracy: 0.6266666666666667
[[33  8 16  4  2]
 [ 7 35 17  3  0]
 [ 8 14 73  9  0]
 [ 8  3  6 47  0]
 [ 2  4  0  1  0]]
              precision    recall  f1-score   support

       heart       0.57      0.52      0.55        63
        long       0.55      0.56      0.56        62
        oval       0.65      0.70      0.68       104
       round       0.73      0.73      0.73        64
      square       0.00      0.00      0.00         7

    accuracy                           0.63       300
   macro avg       0.50      0.50      0.50       300
weighted avg       0.62      0.63      0.62       300



In [165]:
# train a MLP classifier and print the accuracy and confusion matrix
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)
mlp.fit(X_train_pca, Y_train)
Y_pred = mlp.predict(X_test_pca)
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

Accuracy: 0.6366666666666667
[[42  6  7  8  0]
 [ 6 37 15  4  0]
 [12 18 62 11  1]
 [ 9  0  5 50  0]
 [ 2  3  1  1  0]]
              precision    recall  f1-score   support

       heart       0.59      0.67      0.63        63
        long       0.58      0.60      0.59        62
        oval       0.69      0.60      0.64       104
       round       0.68      0.78      0.72        64
      square       0.00      0.00      0.00         7

    accuracy                           0.64       300
   macro avg       0.51      0.53      0.52       300
weighted avg       0.63      0.64      0.63       300



C:\Users\qayse\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:684: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [166]:
# save the lda model to disk 
import pickle
filename = 'lda_model.sav'
pickle.dump(lda, open(filename, 'wb'))

In [167]:
from conversion_to_data_frame import *
test_photo = 'test2.jpg'
df = pd.DataFrame(columns = ['0','1','2','3','4','5','6','7','8','9','10','11',	'12',	'13',	'14',	'15',	'16','17',
                             '18',	'19',	'20',	'21',	'22',	'23',	'24','25',	'26',	'27',	'28',	'29',
                             '30',	'31',	'32',	'33',	'34',	'35',	'36',	'37',	'38',	'39',	'40',	'41',
                             '42',	'43',	'44',	'45',	'46',	'47',	'48',	'49',	'50',	'51',	'52',	'53',
                             '54',	'55',	'56',	'57',	'58',	'59',	'60',	'61',	'62',	'63',	'64',	'65',
                             '66',	'67',	'68',	'69',	'70',	'71',	'72',	'73',	'74',	'75',	'76',	'77',
                             '78',	'79',	'80',	'81',	'82',	'83',	'84',	'85',	'86',	'87',	'88',	'89',
                             '90',	'91',	'92',	'93',	'94',	'95',	'96',	'97',	'98',	'99',	'100',	'101',
                             '102',	'103',	'104',	'105',	'106',	'107',	'108',	'109',	'110',	'111',	'112',	'113',
                             '114',	'115',	'116',	'117',	'118',	'119',	'120',	'121',	'122',	'123',	'124',	'125',
                             '126',	'127',	'128',	'129',	'130',	'131',	'132',	'133',	'134',	'135',	'136',	'137',
                             '138',	'139',	'140',	'141',	'142',	'143','A1','A2','A3','A4','A5','A6','A7','A8','A9',
                            'A10','A11','A12','A13','A14','A15','A16','Width','Height','H_W_Ratio','Jaw_width','J_F_Ratio',
                             'MJ_width','MJ_J_width'])

style_df = pd.DataFrame()
style_df = pd.DataFrame(columns = ['face_shape','hair_length','location','filename','score'])
make_face_df_save(test_photo,2305,df)
df.head()


[[[208 208 208]
  [203 203 203]
  [205 205 205]
  ...
  [200 200 200]
  [199 199 199]
  [202 202 202]]

 [[205 205 205]
  [200 200 200]
  [201 201 201]
  ...
  [197 197 197]
  [196 196 196]
  [199 199 199]]

 [[206 206 206]
  [200 200 200]
  [202 202 202]
  ...
  [198 198 198]
  [197 197 197]
  [200 200 200]]

 ...

 [[203 203 203]
  [199 199 199]
  [199 199 199]
  ...
  [191 130  83]
  [188 130  82]
  [193 135  87]]

 [[204 204 204]
  [201 201 201]
  [200 200 200]
  ...
  [191 133  87]
  [189 133  86]
  [194 138  91]]

 [[205 205 205]
  [202 202 202]
  [202 202 202]
  ...
  [195 139  92]
  [195 139  92]
  [198 144  97]]]
[{'chin': [(163, 205), (163, 230), (165, 254), (168, 280), (178, 303), (193, 324), (211, 343), (231, 360), (252, 367), (275, 363), (296, 346), (315, 329), (331, 309), (342, 285), (347, 259), (349, 233), (351, 208)], 'left_eyebrow': [(177, 189), (190, 183), (205, 183), (219, 187), (232, 195)], 'right_eyebrow': [(274, 195), (290, 190), (306, 187), (322, 188), (335, 196)

0      1     2      3     4      5     6      7     8      9  ...  \
2305  79.0  101.0  80.0  120.0  81.0  140.0  84.0  160.0  92.0  178.0  ...   

            A14        A15        A16       Width      Height  H_W_Ratio  \
2305  39.610688  34.418364  30.367637  149.030198  216.148097   1.450364   

      Jaw_width  J_F_Ratio  MJ_width  MJ_J_width  
2305  68.007353   0.456333     122.0    1.793924  

[1 rows x 167 columns]

In [168]:
# load the model from disk and than predict the face shape

# loaded_model = pickle.load(open('lda_model.sav', 'rb'))
# result = loaded_model.predict(df)
# print(result)
with open('lda_model.sav', 'rb') as f:
    model = pickle.load(f)

# use the model to make a prediction
input_data = df # some input data for the model
prediction = model.predict(input_data)


ValueError: Expected 2D array, got scalar array instead:
array=Ellipsis.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.