In [14]:
import pandas as pd
import numpy as np


In [15]:
df = pd.read_csv('all_features_2.csv', index_col= None)
df = df.drop('Unnamed: 0', axis=1)
# randomize the data
df = df.sample(frac=1).reset_index(drop=True)
df.head()

0      1     2      3     4      5     6      7     8      9  ...  \
0  69.0  113.0  71.0  132.0  76.0  150.0  82.0  167.0  89.0  183.0  ...   
1  71.0   94.0  72.0  116.0  74.0  138.0  77.0  159.0  85.0  178.0  ...   
2  81.0   85.0  84.0  106.0  89.0  126.0  93.0  145.0  99.0  163.0  ...   
3  77.0  105.0  79.0  125.0  82.0  144.0  86.0  164.0  93.0  183.0  ...   
4  77.0  113.0  78.0  133.0  80.0  152.0  84.0  171.0  90.0  190.0  ...   

        Width      Height  H_W_Ratio  Jaw_width  J_F_Ratio    MJ_width  \
0  143.003497  212.037733   1.482745  71.253070   0.498261  117.209215   
1  145.086181  202.158354   1.393367  65.375837   0.450600  117.345643   
2  142.003521  180.044439   1.267887  59.008474   0.415542  106.004717   
3  145.003448  228.078934   1.572921  67.007462   0.462109  120.016666   
4  162.077142  242.008264   1.493167  78.006410   0.481292  135.000000   

   MJ_J_width  filenum                   filename  classified_shape  
0    1.644971     1465           mila kunis 7.jpg             round  
1    1.794939      230              Ciara (6).jpg             heart  
2    1.796432     1247      Arizona Muse (14).jpg             round  
3    1.791094      757       Jessica Alba (6).jpg              oval  
4    1.730627      655  Jennifer Aniston (27).jpg              oval  

[5 rows x 170 columns]

In [16]:
from sklearn import metrics
from sklearn.metrics import pairwise_distances
from sklearn.preprocessing import normalize
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn import ensemble
from sklearn import linear_model
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler  
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.decomposition import PCA 

In [17]:
data = df.dropna(axis=0, how='any')
X = data
X = X.drop(['filenum','filename','classified_shape'] , axis = 1)
X_norm = normalize(X)
Y = data['classified_shape']
Y.head()

0    round
1    heart
2    round
3     oval
4     oval
Name: classified_shape, dtype: object

In [18]:
scaler = StandardScaler()  
scaler.fit(X)  

X = scaler.transform(X)

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,Y,
    test_size=0.25,
    random_state=1200)

In [20]:
n_components = 18
pca = PCA(n_components=n_components, svd_solver='randomized',
          whiten=True).fit(X)

X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)

In [21]:
# #Remove PCA 
X_train_pca = X_train
X_test_pca = X_test

In [22]:
# train a LDA classifier and print the accuracy and confusion matrix
lda = LinearDiscriminantAnalysis()
lda.fit(X_train_pca, Y_train)
Y_pred = lda.predict(X_test_pca)
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))


Accuracy: 0.6466666666666666
[[28  6 23  3  0]
 [ 5 41 26  4  0]
 [ 8  7 63  4  2]
 [ 6  4  3 61  1]
 [ 3  0  1  0  1]]
              precision    recall  f1-score   support

       heart       0.56      0.47      0.51        60
        long       0.71      0.54      0.61        76
        oval       0.54      0.75      0.63        84
       round       0.85      0.81      0.83        75
      square       0.25      0.20      0.22         5

    accuracy                           0.65       300
   macro avg       0.58      0.55      0.56       300
weighted avg       0.66      0.65      0.64       300



In [23]:
# train a MLP classifier and print the accuracy and confusion matrix
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)
mlp.fit(X_train_pca, Y_train)
Y_pred = mlp.predict(X_test_pca)
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

Accuracy: 0.6666666666666666
[[31  5 17  7  0]
 [10 49 13  3  1]
 [11  2 60  8  3]
 [ 5  3  7 60  0]
 [ 1  1  2  1  0]]
              precision    recall  f1-score   support

       heart       0.53      0.52      0.53        60
        long       0.82      0.64      0.72        76
        oval       0.61      0.71      0.66        84
       round       0.76      0.80      0.78        75
      square       0.00      0.00      0.00         5

    accuracy                           0.67       300
   macro avg       0.54      0.54      0.54       300
weighted avg       0.67      0.67      0.67       300



C:\Users\qayse\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:684: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [24]:
# save the lda model to disk 

import pickle
filename = 'mlp_model.sav'
pickle.dump(mlp, open(filename, 'wb'))

In [25]:
from conversion_to_data_frame import *
test_photo = 'test2.jpg'
df = pd.DataFrame(columns = ['0','1','2','3','4','5','6','7','8','9','10','11',	'12',	'13',	'14',	'15',	'16','17',
                             '18',	'19',	'20',	'21',	'22',	'23',	'24','25',	'26',	'27',	'28',	'29',
                             '30',	'31',	'32',	'33',	'34',	'35',	'36',	'37',	'38',	'39',	'40',	'41',
                             '42',	'43',	'44',	'45',	'46',	'47',	'48',	'49',	'50',	'51',	'52',	'53',
                             '54',	'55',	'56',	'57',	'58',	'59',	'60',	'61',	'62',	'63',	'64',	'65',
                             '66',	'67',	'68',	'69',	'70',	'71',	'72',	'73',	'74',	'75',	'76',	'77',
                             '78',	'79',	'80',	'81',	'82',	'83',	'84',	'85',	'86',	'87',	'88',	'89',
                             '90',	'91',	'92',	'93',	'94',	'95',	'96',	'97',	'98',	'99',	'100',	'101',
                             '102',	'103',	'104',	'105',	'106',	'107',	'108',	'109',	'110',	'111',	'112',	'113',
                             '114',	'115',	'116',	'117',	'118',	'119',	'120',	'121',	'122',	'123',	'124',	'125',
                             '126',	'127',	'128',	'129',	'130',	'131',	'132',	'133',	'134',	'135',	'136',	'137',
                             '138',	'139',	'140',	'141',	'142',	'143','A1','A2','A3','A4','A5','A6','A7','A8','A9',
                            'A10','A11','A12','A13','A14','A15','A16','Width','Height','H_W_Ratio','Jaw_width','J_F_Ratio',
                             'MJ_width','MJ_J_width'])

style_df = pd.DataFrame()
style_df = pd.DataFrame(columns = ['face_shape','hair_length','location','filename','score'])
make_face_df_save(test_photo,2305,df)
df.head()


[[[208 208 208]
  [203 203 203]
  [205 205 205]
  ...
  [200 200 200]
  [199 199 199]
  [202 202 202]]

 [[205 205 205]
  [200 200 200]
  [201 201 201]
  ...
  [197 197 197]
  [196 196 196]
  [199 199 199]]

 [[206 206 206]
  [200 200 200]
  [202 202 202]
  ...
  [198 198 198]
  [197 197 197]
  [200 200 200]]

 ...

 [[203 203 203]
  [199 199 199]
  [199 199 199]
  ...
  [191 130  83]
  [188 130  82]
  [193 135  87]]

 [[204 204 204]
  [201 201 201]
  [200 200 200]
  ...
  [191 133  87]
  [189 133  86]
  [194 138  91]]

 [[205 205 205]
  [202 202 202]
  [202 202 202]
  ...
  [195 139  92]
  [195 139  92]
  [198 144  97]]]
[{'chin': [(163, 205), (163, 230), (165, 254), (168, 280), (178, 303), (193, 324), (211, 343), (231, 360), (252, 367), (275, 363), (296, 346), (315, 329), (331, 309), (342, 285), (347, 259), (349, 233), (351, 208)], 'left_eyebrow': [(177, 189), (190, 183), (205, 183), (219, 187), (232, 195)], 'right_eyebrow': [(274, 195), (290, 190), (306, 187), (322, 188), (335, 196)

0      1     2      3     4      5     6      7     8      9  ...  \
2305  79.0  101.0  80.0  120.0  81.0  140.0  84.0  160.0  92.0  178.0  ...   

            A14        A15        A16       Width      Height  H_W_Ratio  \
2305  39.610688  34.418364  30.367637  149.030198  216.148097   1.450364   

      Jaw_width  J_F_Ratio  MJ_width  MJ_J_width  
2305  68.007353   0.456333     122.0    1.793924  

[1 rows x 167 columns]

In [26]:
#load the model from disk and than predict the face shape

loaded_model = pickle.load(open('mlp_model.sav', 'rb'))
result = loaded_model.predict(df)
print(result)



['long']


C:\Users\qayse\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but MLPClassifier was fitted without feature names
  warnings.warn(
