In [2]:
import pandas as pd
import numpy as np


In [3]:
df = pd.read_csv('all_features.csv', index_col= None)
df = df.drop('Unnamed: 0', axis=1)
df.shape

(1524, 170)

In [4]:
from sklearn import metrics
from sklearn.metrics import pairwise_distances
from sklearn.preprocessing import normalize
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn import ensemble
from sklearn import linear_model
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler  
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.decomposition import PCA 

In [5]:
data = df.dropna(axis=0, how='any')
X = data
X = X.drop(['filenum','filename','classified_shape'] , axis = 1)
X_norm = normalize(X)
Y = data['classified_shape']

In [6]:
scaler = StandardScaler()  
scaler.fit(X)  

X = scaler.transform(X)

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,Y,
    test_size=0.25,
    random_state=1200)

In [8]:
n_components = 18
pca = PCA(n_components=n_components, svd_solver='randomized',
          whiten=True).fit(X)

X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)

In [9]:
# #Remove PCA 
X_train_pca = X_train
X_test_pca = X_test

In [20]:
# train a random forest classifier and print the accuracy and confusion matrix
rf = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=0)
rf.fit(X_train_pca, Y_train)
Y_pred = rf.predict(X_test_pca)
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))


Accuracy: 0.5851063829787234
[[41  3 21  6  4]
 [ 3 32 21  2 10]
 [10  8 55  9 17]
 [ 3  1  3 45 10]
 [ 4  3  7 11 47]]
              precision    recall  f1-score   support

       heart       0.67      0.55      0.60        75
        long       0.68      0.47      0.56        68
        oval       0.51      0.56      0.53        99
       round       0.62      0.73      0.67        62
      square       0.53      0.65      0.59        72

    accuracy                           0.59       376
   macro avg       0.60      0.59      0.59       376
weighted avg       0.60      0.59      0.58       376



In [21]:
# train a KNN classifier and print the accuracy and confusion matrix
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_pca, Y_train)
Y_pred = knn.predict(X_test_pca)
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

Accuracy: 0.601063829787234
[[47  8 12  4  4]
 [ 7 44 11  1  5]
 [15 11 56  8  9]
 [ 5  2  3 46  6]
 [ 7 15  7 10 33]]
              precision    recall  f1-score   support

       heart       0.58      0.63      0.60        75
        long       0.55      0.65      0.59        68
        oval       0.63      0.57      0.60        99
       round       0.67      0.74      0.70        62
      square       0.58      0.46      0.51        72

    accuracy                           0.60       376
   macro avg       0.60      0.61      0.60       376
weighted avg       0.60      0.60      0.60       376



c:\Users\aksde\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [22]:
# train a LDA classifier and print the accuracy and confusion matrix
lda = LinearDiscriminantAnalysis()
lda.fit(X_train_pca, Y_train)
Y_pred = lda.predict(X_test_pca)
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))


Accuracy: 0.6117021276595744
[[48  3 17  2  5]
 [ 7 31 19  0 11]
 [14  7 67  3  8]
 [ 4  3  7 41  7]
 [ 7  8  8  6 43]]
              precision    recall  f1-score   support

       heart       0.60      0.64      0.62        75
        long       0.60      0.46      0.52        68
        oval       0.57      0.68      0.62        99
       round       0.79      0.66      0.72        62
      square       0.58      0.60      0.59        72

    accuracy                           0.61       376
   macro avg       0.63      0.61      0.61       376
weighted avg       0.62      0.61      0.61       376



In [23]:
# train a MLP classifier and print the accuracy and confusion matrix
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)
mlp.fit(X_train_pca, Y_train)
Y_pred = mlp.predict(X_test_pca)
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

Accuracy: 0.6090425531914894
[[40  3 20  9  3]
 [ 8 42  7  1 10]
 [15  8 66  3  7]
 [ 4  3  6 41  8]
 [ 1 11 12  8 40]]
              precision    recall  f1-score   support

       heart       0.59      0.53      0.56        75
        long       0.63      0.62      0.62        68
        oval       0.59      0.67      0.63        99
       round       0.66      0.66      0.66        62
      square       0.59      0.56      0.57        72

    accuracy                           0.61       376
   macro avg       0.61      0.61      0.61       376
weighted avg       0.61      0.61      0.61       376



c:\Users\aksde\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [24]:
# train a logistic regression classifier and print the accuracy and confusion matrix
logreg = linear_model.LogisticRegression(C=1e5)
logreg.fit(X_train_pca, Y_train)
Y_pred = logreg.predict(X_test_pca)
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))


Accuracy: 0.601063829787234
[[43  4 17  4  7]
 [ 8 34 12  0 14]
 [16  7 61  8  7]
 [ 5  3  4 42  8]
 [ 4 10  7  5 46]]
              precision    recall  f1-score   support

       heart       0.57      0.57      0.57        75
        long       0.59      0.50      0.54        68
        oval       0.60      0.62      0.61        99
       round       0.71      0.68      0.69        62
      square       0.56      0.64      0.60        72

    accuracy                           0.60       376
   macro avg       0.61      0.60      0.60       376
weighted avg       0.60      0.60      0.60       376



c:\Users\aksde\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [25]:
# train a gradient boosting classifier and print the accuracy and confusion matrix
gb = ensemble.GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=1, random_state=0)
gb.fit(X_train_pca, Y_train)
Y_pred = gb.predict(X_test_pca)
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))


Accuracy: 0.5292553191489362
[[38  3 20  8  6]
 [ 8 31 18  2  9]
 [15  9 50  7 18]
 [ 4  2  7 40  9]
 [ 5  8  5 14 40]]
              precision    recall  f1-score   support

       heart       0.54      0.51      0.52        75
        long       0.58      0.46      0.51        68
        oval       0.50      0.51      0.50        99
       round       0.56      0.65      0.60        62
      square       0.49      0.56      0.52        72

    accuracy                           0.53       376
   macro avg       0.54      0.53      0.53       376
weighted avg       0.53      0.53      0.53       376



In [26]:
# train a SVM classifier and print the accuracy and confusion matrix
from sklearn.svm import SVC
svm = SVC(kernel='linear')
svm.fit(X_train_pca, Y_train)
Y_pred = svm.predict(X_test_pca)
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
 

Accuracy: 0.5930851063829787
[[41  6 15  7  6]
 [10 36 13  0  9]
 [16  7 65  6  5]
 [ 6  3  8 40  5]
 [ 5 10  9  7 41]]
              precision    recall  f1-score   support

       heart       0.53      0.55      0.54        75
        long       0.58      0.53      0.55        68
        oval       0.59      0.66      0.62        99
       round       0.67      0.65      0.66        62
      square       0.62      0.57      0.59        72

    accuracy                           0.59       376
   macro avg       0.60      0.59      0.59       376
weighted avg       0.59      0.59      0.59       376

